### ISSUE TITLE
default values should be passed to Tinybird

### ISSUE THREAD

**Issue by tobiaslins** [chronark/zod-bird#5]
Currently when defining an endpoint like following
```
export const publishEvent = tb.buildIngestEndpoint({
  datasource: "events__v1",
  event: z.object({
    id: z.string(),
    metadata: z.string().optional().default(""),
  }),
});
```
and call it 
```
publishEvent({ id: "123" })
```

Tinybird will reject it because the parsed value (with defaults) is not passed.

**Comment by chronark** [comment]
Fixed in https://github.com/chronark/zod-bird/releases/tag/v0.2.1
